# The rows each player starts with
player-starting-rows: 1

vault-pricing: true

#If vault-pricing is false, then this is useless
personal-storage:
  price: 500
  upgrade-multiplier: 1.2 # The upgrade cost is calculated by (original price) * (upgrade multiplier) ^ (num. of rows)

chunk-storage:
  price: 200
  upgrade-multiplier: 1.05

group-storage:
    price: 400
    upgrade-multiplier: 1.1

towny: false


