# The default number of group inventories that a player has access to:
default-player-groups: 7

# The rows each player starts with
player-starting-rows: 1

vault-pricing: true

#If vault-pricing is false, then this is useless
personal-storage:

  purchaseable: true  # If this is true, then players can buy a personal storage and upgrade it with money

  price: 500

  upgrade-multiplier: 1.2 # The upgrade cost is calculated by (original price) * (upgrade multiplier) ^ (num. of rows)

chunk-storage:

  purchaseable: true

  price: 200

  upgrade-multiplier: 1.05

group-storage:

    purchaseable: true

    price: 400

    upgrade-multiplier: 1.1

