name: StoragePlus
version: 1.0
main: com.somemone.storageplus.StoragePlus
api-version: 1.16

commands:
  cstorage:
    description: Manage your Chunk Storage
    aliases: [cs, chunkstorage]
    usage: "Usage: /cstorage [upgrade|create]"

  pstorage:
    description: Manage your Personal Storage
    aliases: [ps, personalstorage]
    usage: "Usage: /pstorage [upgrade|create]"

  gstorage:
    description: Manage your Group Storage(s)
    aliases: [gs, groupstorage]
    usage: "Usage: /gstorage [create|remove|invite|setowner|upgrade]"

  stadmin:
    description: Admin Commands for BigVentories
    aliases: sta
    usage: "Usage: /stadmin [save|load|view|delete|getplayers]"
    permission: "sta.use"

  staccept:
    description: Accept command for Group Storages

permissions:
  sta.use:
    description: Allows you to use the /bva command
    default: op

  sta.getplayers:
    description: Allows you to view the players in a group
    default: op

  sta.view:
    description: Allows you to view all types of inventories.
    default: op

  sta.delete:
    description: Allows the player to delete inventories
    default: op

  sta.save:
    description: Allows the player to save the game
    default: op

  sta.load:
    description: Allows the player to load the game
    default: op

  sta.voucher:
    description: Allows user to create vouchers
    default: op

  sta.*:
    description: Allows you to use all bva commands
    default: op
    children:
      sta.view: true
      sta.use: true
      sta.delete: true
      sta.save: true
      sta.load: true
      sta.getplayers: true







